### ISSUE TITLE
help .zip not found

### ISSUE THREAD

**Issue by robin1214** [alos-source/UnifiedScreenControl#3]
problem：

In the TIA Portal, click on the  "Update" button in the "Toolbox" > "My Controls" task card.

info out：
File C:\Program Files\Siemens\Automation\Portal V17\Data\Hmi\CustomControls\{B5EE6DEF-00EB-4880-AC1E-39A6AF506363}.zip not found!,12/9/2022,12:21:39 PM

What's the reason

**Comment by alos-source** [comment]
@robin1214 Have you been able to find out, what was wrong?
